# Generated by Django 3.0.3 on 2020-06-01 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200601_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 6, 54, 41, 506015, tzinfo=utc)),
        ),
    ]
