# Generated by Django 3.0.3 on 2020-06-01 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200601_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 8, 44, 40, 7642, tzinfo=utc)),
        ),
    ]
