# Generated by Django 3.0.3 on 2020-06-04 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200601_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 2, 23, 16, 744552, tzinfo=utc)),
        ),
    ]
